### ISSUE TITLE
can't load neuron package from python prompt

### ISSUE THREAD

**Issue by wvangeit** [pramodskumbhar/spack-packages#58]
When installing the neuron package (with python support, which is the default), a python prompt can't find the 'neuron' module.
It works when I run nrniv -python, but when I run 'python' and then 'import neuron' it can't find the neuron package.
(I did load the correct spack python package that was used to compile neuron)
Probably some PYTHONPATH that needs to be set (or the python part of neuron should be installed using pip).

**Comment by pramodskumbhar** [comment]
Oh ok, I have always used `nrniv -python` way. The missing is `PYTHONPATH` environment variable. I will fix that.
