### ISSUE TITLE
Better naming for neurodamus variant `compile`

### ISSUE THREAD

**Issue by sharkovsky** [pramodskumbhar/spack-packages#6]
The issue that I've observed is the following:
1) spack install coreneuron will also install a neurodamus, but with the `-compile` variant
2) spack install neurodamus to produce the `special` executable requires the `+compile` variant.

Now, when I want to use the `special` I need to remember that I should `spack load neurodamus +compile` variant, because if I simply do `spack load neurodamus` then it loads the one built by coreneuron and it doesn't have a special in its path (also, it yells about module conflict). 

It took me a while to realize that `+compile` meant that it would create the `special` and put it in my path. Is there a better name?

**Comment by pramodskumbhar** [comment]
I agree...

I know how to avoid this confusion when creating `modules` for end users. We can add following configurations in `modules.yaml` : 

```
  tcl:
    blacklist: ['neurodamus-compile']
```

this means there won't be any module file for neurodamus without special. I have to check if this avoid loading `-compile` modules altogether. (note that `spack find` will still show the all packages)

**Comment by pramodskumbhar** [comment]
@sharkovsky : I have changed variant name from `compile` to `special`. This is still bit ugly in the sense that there will be two installations for neurodamus (one with only mod files).

Once @fouriaux finishes work on nrnivmodl like workflow for coreneuron, this will be removed. Good approach for now is to blacklist the module for `neurodamus ~special` .

For now closing this issue.
