### ISSUE TITLE
Possible reproducibility problem in neuron package

### ISSUE THREAD

**Issue by wvangeit** [pramodskumbhar/spack-packages#60]
I guess this could change results ?

https://github.com/pramodskumbhar/spack-packages/blob/develop/packages/neuron/package.py#L77

Maybe you can make a coreneuron variant ?

**Comment by pramodskumbhar** [comment]
Yes. When I created PR to official Spack repo I removed that. I will create coreneuron variant.

**Comment by pramodskumbhar** [comment]
@wvangeit : I added `coreneuron` variant which is `off` by default. Note that when we add new variants or change version names then checksum/hash of package changes. So when you pull, remove old versions.
